SELECT ORGANIZATION_ID, ORGANIZATION_CODE, ORGANIZATION_NAME, OPERATING_UNIT, LEGAL_ENTITY
FROM APPS.ORG_ORGANIZATION_DEFINITIONS INV
WHERE INV.ORGANIZATION_ID = 105;

SELECT DISTINCT 
  RTV.TO_ORGANIZATION_ID,
  RTV.RCV_SHIPMENT_NUM RECEIPT_NUM,
  SHIPMENT_HEADER_ID,
  SYSDATE              SHIPPED_DATE
FROM RCV_TRANSACTIONS_V RTV
WHERE 1=1
  AND RTV.TO_ORGANIZATION_ID = 136
  --AND RTV.RCV_SHIPMENT_NUM = 20
  AND (
    EXISTS (
      SELECT 1
      FROM XXFR_WMS_TB_COF_CEGA_HEADER XTCCH
      WHERE STATUS IN ('CON', 'CAN')
        AND XTCCH.RECEIPT_NUM = RTV.RCV_SHIPMENT_NUM
        AND XTCCH.ORGANIZATION_ID = RTV.TO_ORGANIZATION_ID
    ) OR
    NOT EXISTS (
      SELECT 1
      FROM XXFR_WMS_TB_COF_CEGA_HEADER XTCCH
      WHERE 1=1
        AND XTCCH.RECEIPT_NUM = RTV.RCV_SHIPMENT_NUM
        AND XTCCH.ORGANIZATION_ID = RTV.TO_ORGANIZATION_ID
    )
  )
ORDER BY 1;

SELECT DISTINCT 
  MSI.INVENTORY_ITEM_ID,
  MSI.SEGMENT1,
  MSI.DESCRIPTION,
  RTV.UNIT_OF_MEASURE,
  --null        line_num,
  MSI.LOT_CONTROL_CODE,
  --null                  shipment_line_id, 
  rtv.quantity
FROM 
  RCV_TRANSACTIONS_V RTV, 
  MTL_SYSTEM_ITEMS MSI
WHERE 1=1
  --and MSI.SEGMENT1 = NVL(W_ITEM, MSI.SEGMENT1)
  AND MSI.ORGANIZATION_ID = RTV.TO_ORGANIZATION_ID
  AND MSI.INVENTORY_ITEM_ID = RTV.ITEM_ID
  AND RTV.SHIPMENT_HEADER_ID = '20012'
  AND ( 
    EXISTS (
      SELECT 1
      FROM XXFR_WMS_TB_COF_CEGA_HEADER XTCCH
      WHERE STATUS IN ('CON', 'CAN')
      AND XTCCH.RECEIPT_NUM = RTV.RCV_SHIPMENT_NUM
      AND XTCCH.ORGANIZATION_ID = RTV.TO_ORGANIZATION_ID
    ) OR NOT EXISTS (
      SELECT 1
      FROM XXFR_WMS_TB_COF_CEGA_HEADER XTCCH
      WHERE XTCCH.RECEIPT_NUM = RTV.RCV_SHIPMENT_NUM
      AND XTCCH.ORGANIZATION_ID = RTV.TO_ORGANIZATION_ID
    )
  )
ORDER BY 2;






  BEGIN
    SELECT *
      --INTO V_OPERATING_UNIT
      FROM APPS.ORG_ORGANIZATION_DEFINITIONS INV
     WHERE INV.ORGANIZATION_ID = P_ORGANIZATION_ID;
  END;



SELECT *
FROM RCV_TRANSACTIONS_V RTV
WHERE 1=1
AND RTV.TO_ORGANIZATION_ID = 122
--AND RTV.RCV_SHIPMENT_NUM = NVL(NULL, RTV.RCV_SHIPMENT_NUM)
AND (EXISTS (SELECT 1
FROM XXFR_WMS_TB_COF_CEGA_HEADER XTCCH
WHERE STATUS IN ('CON', 'CAN')
AND XTCCH.RECEIPT_NUM = RTV.RCV_SHIPMENT_NUM
AND XTCCH.ORGANIZATION_ID = RTV.TO_ORGANIZATION_ID) OR
NOT EXISTS
(SELECT 1
FROM XXFR_WMS_TB_COF_CEGA_HEADER XTCCH
WHERE XTCCH.RECEIPT_NUM = RTV.RCV_SHIPMENT_NUM
AND XTCCH.ORGANIZATION_ID = RTV.TO_ORGANIZATION_ID))
ORDER BY 1;

select organization_id, organization_code, organization_name  from org_access_view  
where responsibility_id = 51417  and resp_application_id = 385  
ORDER BY 2


